defmodule Yepochs.YjsMapArrayConformanceTest do
  @moduledoc """
  Ruling 8.1 — upstream-authored crossing vectors for **maps and arrays**.

  The inherited five cases are text and deletes, so they establish text/delete
  interoperability only. These five were generated by upstream `yjs` 13.6.32
  (`conformance/map_array_corpus.mjs`) so the claim for maps and arrays rests on
  the same kind of evidence rather than on the text vectors by association.
  """
  use ExUnit.Case, async: true

  alias Yelixer.BlockStore
  alias Yelixer.Doc
  alias Yelixer.Encoding
  alias Yelixer.Types.Array
  alias Yelixer.Types.YMap
  alias Yepochs.Algorithm
  alias Yepochs.Bridge
  alias Yepochs.Snapshotter
  alias Yepochs.Update

  @fixtures Path.join(__DIR__, "fixtures/yjs-v1")
  @map_cases [
    "006-map-concurrent-distinct-keys",
    "007-map-sequential-overwrite",
    "008-map-delete-key"
  ]
  @array_cases ["009-array-sequential-inserts", "010-array-delete-element"]

  defp updates(name) do
    Path.join([@fixtures, name, "updates.hex"])
    |> File.read!()
    |> String.split("\n", trim: true)
    |> Enum.map(&Base.decode16!(&1, case: :lower))
  end

  defp assemble(name) do
    Enum.reduce(updates(name), Doc.new(client_id: 1), fn u, d ->
      {:ok, d} = Encoding.apply_update(d, u)
      d
    end)
  end

  defp expected(name) do
    Path.join([@fixtures, name, "expected_view.json"]) |> File.read!() |> String.trim()
  end

  test "the map and array corpus is present — a positive control on the loader" do
    for name <- @map_cases ++ @array_cases do
      assert File.dir?(Path.join(@fixtures, name)), "missing fixture #{name}"
      assert updates(name) != [], "#{name} has no updates"
    end
  end

  test "upstream-authored MAP updates decode and assemble to upstream's own view" do
    for name <- @map_cases do
      doc = assemble(name)
      for u <- updates(name), do: assert({:ok, %Update{}} = Update.decode(u))

      json = expected(name)

      for {k, v} <- extract_pairs(json) do
        assert YMap.get(doc, "m", k) == v, "#{name}: key #{k}"
      end
    end
  end

  test "upstream-authored ARRAY updates assemble to upstream's own view" do
    for name <- @array_cases do
      doc = assemble(name)
      expected_list = extract_list(expected(name))
      assert Array.to_list(doc, "a") == expected_list, "#{name}"
    end
  end

  test "a map document assembled from foreign bytes snapshots without loss" do
    for name <- @map_cases do
      doc = assemble(name)
      {:ok, s} = Snapshotter.snapshot(doc, [])
      {:ok, out} = Encoding.apply_update(Doc.new(client_id: 9), s.update)

      for {k, v} <- extract_pairs(expected(name)) do
        assert YMap.get(out, "m", k) == v, "#{name}: key #{k} lost by snapshot"
      end
    end
  end

  test "an array document assembled from foreign bytes snapshots without loss" do
    for name <- @array_cases do
      doc = assemble(name)
      {:ok, s} = Snapshotter.snapshot(doc, [])
      {:ok, out} = Encoding.apply_update(Doc.new(client_id: 9), s.update)
      assert Array.to_list(out, "a") == extract_list(expected(name)), "#{name}"
    end
  end

  test "a MAP edit crosses a bridge built from a foreign snapshot" do
    for name <- @map_cases do
      doc = assemble(name)
      {:ok, s} = Snapshotter.snapshot(doc, [])
      {:ok, target} = Encoding.apply_update(Doc.new(client_id: 500), s.update)
      {:ok, bridge} = Bridge.attach(s.derivation, "origin", "derived", Algorithm.snapshot())

      edited = YMap.set(doc, "m", "crossed", "yes")
      update = Encoding.encode_diff(edited, BlockStore.state_vector(doc.store))

      assert {:ok, c} =
               Yepochs.cross(bridge, update, doc, target,
                 from: :left,
                 author: 4242,
                 receipt_ref: "map-#{name}"
               )

      out =
        case c.update do
          <<>> ->
            target

          u ->
            (fn ->
               {:ok, d} = Encoding.apply_update(target, u)
               d
             end).()
        end

      assert YMap.get(out, "m", "crossed") == "yes", "#{name} (#{c.mode})"
    end
  end

  test "an ARRAY edit crosses a bridge built from a foreign snapshot" do
    for name <- @array_cases do
      doc = assemble(name)
      {:ok, s} = Snapshotter.snapshot(doc, [])
      {:ok, target} = Encoding.apply_update(Doc.new(client_id: 500), s.update)
      {:ok, bridge} = Bridge.attach(s.derivation, "origin", "derived", Algorithm.snapshot())

      edited = Array.insert(doc, "a", 0, ["Q"])
      update = Encoding.encode_diff(edited, BlockStore.state_vector(doc.store))

      assert {:ok, c} =
               Yepochs.cross(bridge, update, doc, target,
                 from: :left,
                 author: 4242,
                 receipt_ref: "arr-#{name}"
               )

      out =
        case c.update do
          <<>> ->
            target

          u ->
            (fn ->
               {:ok, d} = Encoding.apply_update(target, u)
               d
             end).()
        end

      assert Array.to_list(out, "a") == ["Q" | extract_list(expected(name))],
             "#{name} (#{c.mode})"
    end
  end

  # The fixture views are a fixed shape; parsing them directly keeps this library
  # free of a JSON dependency it does not otherwise need.
  defp extract_pairs(json) do
    Regex.scan(~r/"([^"]+)"\s*:\s*"([^"]*)"/, json)
    |> Enum.map(fn [_, k, v] -> {k, v} end)
    |> Enum.reject(fn {k, _} -> k == "map" end)
  end

  defp extract_list(json) do
    [_, inner] = Regex.run(~r/"array"\s*:\s*\[(.*?)\]/, json)
    Regex.scan(~r/"([^"]*)"/, inner) |> Enum.map(fn [_, v] -> v end)
  end
end
